// generated by stringer -type=ErrorCode; DO NOT EDIT

package codes

import "fmt"

const _ErrorCode_name = "ErrorUnknownErrorConditionFailedErrorCollectionSizeExceededErrorThroughputExceededErrorNotFoundErrorInternalFailureErrorAuthErrorInvalidParameterErrorServiceUnavailableErrorThrottlingErrorResourceInUseErrorExpiredIteratorErrorTrimmedData"

var _ErrorCode_index = [...]uint8{0, 12, 32, 59, 82, 95, 115, 124, 145, 168, 183, 201, 221, 237}

func (i ErrorCode) String() string {
	if i < 0 || i >= ErrorCode(len(_ErrorCode_index)-1) {
		return fmt.Sprintf("ErrorCode(%d)", i)
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
